obstacle_range: 3.5
raytrace_range: 4.0
max_obstacle_height: 1.0
inf_is_valid: true
footprint: [[0.16, 0.29], [-0.16, 0.29], [-0.16, -0.29], [0.16, -0.29]]

inflation_radius: 0.1
costscalingfactor: 1.3

map_topic: /rtabmap/octomap_grid
subscribe_to_updates: true
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: neck_center_body_yaw_frame, data_type: LaserScan, topic: scan_filtered, marking: true, clearing: true}
global_frame: map
robot_base_frame: base_link
always_send_full_costmap: true
