TrajectoryPlannerROS:
  max_vel_x: 0.2
  min_vel_x: 0.1
  max_vel_theta: 1
  min_vel_theta: -1
  min_in_place_vel_theta: 1

  escape_vel: -0.1
  acc_lim_theta: 1
  acc_lim_x: 1
  acc_lim_Y: 1

  holonomic_robot: false

  meter_scoring: true

  xy_goal_tolerance: 0.5
  yaw_goal_tolerance: 1
