DWAPlannerROS:
  acc_lim_x: 1.0
  acc_lim_y: 0
  acc_lim_th: 1.4

  max_trans_vel: 1
  min_trans_vel: 0.1

  max_vel_x: 1
  min_vel_x: -0.1

  max_vel_y: 0
  min_vel_y: 0

  max_rot_vel: 1
  min_rot_vel: 0.0


  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.1

  latch_xy_goal_tolerance: false


  sim_time: 2
  sim_granularity: 0.05
  vx_samples: 10
  vy_samples: 0
  vtheta_samples: 10
  controller_frequency: 10


  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02

  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  oscillation_reset_dist: 0.1

  prune_plan: true
